$ANSIBLE_VAULT;1.1;AES256
39646239616136386130303939633434623831306464643232376563383934353836626261306637
3166306162316637386361363835326132656566616437390a366465383764396333623835633031
34316263313539633533656563393335393833313734623639353061656436653035316466636236
3631613936373236330a646330333433386235383866383437383330653037666563323732386532
66393464313734316337386432353336623865343262626438666232653431353865393362313032
38316531616539653066303937666333313636303732626462646263636434303839643466666434
63336166636430393633323139366633643833343661303531313664343831346564333265646136
65626461393737326537313535626638356364346561326234356135633363666435306563653435
62386239376531623365663331393337636161353162396536333463366537633730623338306431
38353032623230306337626636363464383630373439626538636339643635616363663739393938
36353161643139386461393862646634383661343435366139306634346130323430656234326539
38663665303538666662323338353333626462663965383731623366363036666334646534316465
3866
